name: 05 - SonarQube Analysis

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: SonarSource/sonarqube-scan-action@master
        if: ${{ secrets.SONARQUBE_TOKEN != '' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
